import type { GameConfig } from '@/types/game';

// 2026 FRC Game: "Rebuilt"
// This is intentionally simple — the infrastructure is the deliverable.
// Add more fields here as the game manual is released.
const game2026: GameConfig = {
  year: 2026,
  name: 'Rebuilt',
  season: '2026-2027',
  match: {
    auto: [
      {
        id: 'auto_leave',
        label: 'Left Starting Zone',
        type: 'toggle',
        section: 'auto',
        defaultValue: false,
        pointsPerUnit: 3,
      },
      {
        id: 'auto_coral_l1',
        label: 'Coral Scored (L1)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 3,
      },
      {
        id: 'auto_coral_l2',
        label: 'Coral Scored (L2)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'auto_coral_l3',
        label: 'Coral Scored (L3)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 6,
      },
      {
        id: 'auto_coral_l4',
        label: 'Coral Scored (L4)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 7,
      },
      {
        id: 'auto_path',
        label: 'Autonomous Path',
        type: 'path',
        section: 'auto',
        helpText: 'Draw the robot\'s autonomous path on the field',
      },
    ],
    teleop: [
      {
        id: 'teleop_coral_l1',
        label: 'Coral Scored (L1)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 2,
      },
      {
        id: 'teleop_coral_l2',
        label: 'Coral Scored (L2)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 3,
      },
      {
        id: 'teleop_coral_l3',
        label: 'Coral Scored (L3)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'teleop_coral_l4',
        label: 'Coral Scored (L4)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 5,
      },
      {
        id: 'teleop_algae_net',
        label: 'Algae in Net',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 10,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'teleop_algae_processor',
        label: 'Algae in Processor',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 10,
        defaultValue: 0,
        pointsPerUnit: 6,
      },
      {
        id: 'teleop_defense_rating',
        label: 'Defense Rating',
        type: 'rating',
        section: 'teleop',
        min: 0,
        max: 5,
        defaultValue: 0,
        helpText: '0 = no defense, 5 = outstanding',
      },
      {
        id: 'teleop_driver_skill',
        label: 'Driver Skill',
        type: 'rating',
        section: 'teleop',
        min: 1,
        max: 5,
        defaultValue: 3,
      },
    ],
    endgame: [
      {
        id: 'endgame_climb',
        label: 'Climb Level',
        type: 'select',
        section: 'endgame',
        options: ['None', 'Park', 'Shallow Cage', 'Deep Cage'],
        defaultValue: 'None',
        helpText: 'Highest climb achieved at end of match',
      },
      {
        id: 'endgame_harmony',
        label: 'Harmony Bonus',
        type: 'toggle',
        section: 'endgame',
        defaultValue: false,
        helpText: 'Multiple robots on the same cage',
      },
      {
        id: 'endgame_notes',
        label: 'Endgame Notes',
        type: 'textarea',
        section: 'endgame',
      },
    ],
  },
  pit: [
    {
      id: 'pit_drivetrain',
      label: 'Drivetrain Type',
      type: 'select',
      section: 'general',
      options: ['Swerve', 'Tank', 'Mecanum', 'Other'],
      required: true,
    },
    {
      id: 'pit_weight',
      label: 'Robot Weight (lbs)',
      type: 'counter',
      section: 'general',
      min: 0,
      max: 125,
      defaultValue: 0,
    },
    {
      id: 'pit_max_climb',
      label: 'Max Climb Capability',
      type: 'select',
      section: 'general',
      options: ['None', 'Park', 'Shallow Cage', 'Deep Cage'],
      required: true,
    },
    {
      id: 'pit_auto_count',
      label: 'Number of Auto Routines',
      type: 'counter',
      section: 'general',
      min: 0,
      max: 10,
      defaultValue: 0,
    },
    {
      id: 'pit_auto_description',
      label: 'Auto Description',
      type: 'textarea',
      section: 'general',
    },
    {
      id: 'pit_preferred_role',
      label: 'Preferred Role',
      type: 'select',
      section: 'general',
      options: ['Scorer', 'Defender', 'Feeder', 'Flexible'],
    },
    {
      id: 'pit_overall_impression',
      label: 'Overall Impression',
      type: 'rating',
      section: 'general',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'pit_notes',
      label: 'Additional Notes',
      type: 'textarea',
      section: 'general',
    },
  ],
  field: {
    // Placeholder — replace with actual 2026 field image
    src: '/field-2026.png',
    widthFt: 54.75,
    heightFt: 26.33,
  },
};

export default game2026;
