import type { GameConfig } from '../types/game';

// 2025 FRC Game: "Reefscape"
const game2025: GameConfig = {
  year: 2025,
  name: 'Reefscape',
  season: '2024-2025',
  match: {
    auto: [
      {
        id: 'auto_leave',
        label: 'Left Starting Zone',
        type: 'toggle',
        section: 'auto',
        defaultValue: false,
        pointsPerUnit: 3,
      },
      {
        id: 'auto_failed',
        label: 'Auto Failed',
        type: 'toggle',
        section: 'auto',
        defaultValue: false,
        helpText: 'Robot did not execute auto routine as expected',
      },
      {
        id: 'auto_coral_l1',
        label: 'Coral Scored (L1)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 3,
      },
      {
        id: 'auto_coral_l2',
        label: 'Coral Scored (L2)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'auto_coral_l3',
        label: 'Coral Scored (L3)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 6,
      },
      {
        id: 'auto_coral_l4',
        label: 'Coral Scored (L4)',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 6,
        defaultValue: 0,
        pointsPerUnit: 7,
      },
      {
        id: 'auto_algae_net',
        label: 'Algae in Net',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 4,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'auto_algae_processor',
        label: 'Algae in Processor',
        type: 'counter',
        section: 'auto',
        min: 0,
        max: 4,
        defaultValue: 0,
        pointsPerUnit: 6,
      },
      {
        id: 'auto_path',
        label: 'Autonomous Path',
        type: 'path',
        section: 'auto',
        helpText: "Draw the robot's autonomous path on the field",
      },
    ],
    teleop: [
      {
        id: 'teleop_coral_l1',
        label: 'Coral Scored (L1)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 2,
      },
      {
        id: 'teleop_coral_l2',
        label: 'Coral Scored (L2)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 3,
      },
      {
        id: 'teleop_coral_l3',
        label: 'Coral Scored (L3)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'teleop_coral_l4',
        label: 'Coral Scored (L4)',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 20,
        defaultValue: 0,
        pointsPerUnit: 5,
      },
      {
        id: 'teleop_algae_net',
        label: 'Algae in Net',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 10,
        defaultValue: 0,
        pointsPerUnit: 4,
      },
      {
        id: 'teleop_algae_processor',
        label: 'Algae in Processor',
        type: 'counter',
        section: 'teleop',
        min: 0,
        max: 10,
        defaultValue: 0,
        pointsPerUnit: 6,
      },
      {
        id: 'teleop_defense_rating',
        label: 'Defense Rating',
        type: 'rating',
        section: 'teleop',
        min: 0,
        max: 5,
        defaultValue: 0,
        helpText: '0 = no defense, 5 = outstanding',
      },
      {
        id: 'teleop_driver_skill',
        label: 'Driver Skill',
        type: 'rating',
        section: 'teleop',
        min: 1,
        max: 5,
        defaultValue: 3,
      },
      {
        id: 'flag_defense',
        label: 'Played Defense',
        type: 'toggle',
        section: 'teleop',
        defaultValue: false,
      },
      {
        id: 'flag_passing',
        label: 'Passing / Assisted Partners',
        type: 'toggle',
        section: 'teleop',
        defaultValue: false,
        helpText: 'Coordinated coral / algae passing or defensive assist',
      },
      {
        id: 'flag_penalties',
        label: 'Caused Penalties',
        type: 'toggle',
        section: 'teleop',
        defaultValue: false,
        helpText: 'Robot drew fouls / caused opponent to score extra points',
      },
      {
        id: 'flag_breakdown',
        label: 'Robot Broke Down',
        type: 'toggle',
        section: 'teleop',
        defaultValue: false,
      },
    ],
    endgame: [
      {
        id: 'endgame_climb',
        label: 'Climb Level',
        type: 'select',
        section: 'endgame',
        options: ['None', 'Park', 'Shallow Cage', 'Deep Cage'],
        defaultValue: 'None',
        helpText: 'Highest climb achieved at end of match',
      },
      {
        id: 'endgame_harmony',
        label: 'Harmony Bonus',
        type: 'toggle',
        section: 'endgame',
        defaultValue: false,
        helpText: 'Multiple robots on the same cage (+5 pts per pair)',
      },
      {
        id: 'endgame_notes',
        label: 'Endgame Notes',
        type: 'textarea',
        section: 'endgame',
      },
    ],
  },
  pit: [
    {
      id: 'pit_drivetrain',
      label: 'Drivetrain Type',
      type: 'select',
      section: 'general',
      options: ['Swerve', 'Tank', 'Mecanum', 'Other'],
      required: true,
    },
    {
      id: 'pit_weight',
      label: 'Robot Weight (lbs)',
      type: 'counter',
      section: 'general',
      min: 0,
      max: 125,
      defaultValue: 0,
    },
    {
      id: 'pit_max_climb',
      label: 'Max Climb Capability',
      type: 'select',
      section: 'general',
      options: ['None', 'Park', 'Shallow Cage', 'Deep Cage'],
      required: true,
    },
    {
      id: 'pit_can_harmony',
      label: 'Can Harmony?',
      type: 'toggle',
      section: 'general',
      defaultValue: false,
    },
    {
      id: 'pit_reef_levels',
      label: 'Highest Reef Level',
      type: 'select',
      section: 'general',
      options: ['None', 'L1', 'L2', 'L3', 'L4'],
      required: true,
    },
    {
      id: 'pit_can_score_algae',
      label: 'Scores Algae?',
      type: 'toggle',
      section: 'general',
      defaultValue: false,
    },
    {
      id: 'pit_turret',
      label: 'Has Turret?',
      type: 'toggle',
      section: 'general',
      defaultValue: false,
      helpText: 'Mechanism can rotate/aim without turning the whole robot',
    },
    {
      id: 'pit_dumper',
      label: 'Has Dumper?',
      type: 'toggle',
      section: 'general',
      defaultValue: false,
      helpText: 'Can dump game pieces in bulk (vs. precise individual placement)',
    },
    {
      id: 'pit_auto_count',
      label: 'Number of Auto Routines',
      type: 'counter',
      section: 'general',
      min: 0,
      max: 10,
      defaultValue: 0,
    },
    {
      id: 'pit_auto_description',
      label: 'Auto Description',
      type: 'textarea',
      section: 'general',
    },
    {
      id: 'pit_preferred_role',
      label: 'Preferred Role',
      type: 'select',
      section: 'general',
      options: ['Scorer', 'Defender', 'Feeder', 'Flexible'],
    },
    {
      id: 'pit_overall_impression',
      label: 'Overall Impression',
      type: 'rating',
      section: 'general',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'pit_notes',
      label: 'Additional Notes',
      type: 'textarea',
      section: 'general',
    },
  ],
  field: {
    src: '/NutScout/field-2025.png',
    widthFt: 54.75,
    heightFt: 26.33,
  },
};

export default game2025;
